import Head from "next/head";
import Layout from "../components/Layout";
import styled from "@emotion/styled";
import { createCurriculaObject } from "../utils";

const Section = styled.section`
  max-width: 768px;
  margin: 0 auto;
  padding: 0.5rem 1rem;
  h2 {
    text-align: center;
    margin: 0;
  }
  p {
    margin: 0.5rem 0;
  }
  @media (min-width: 640px) {
    h2 {
      margin: 0.5rem;
    }
    p {
      margin: 1rem 0;
    }
  }
`;

export default function Home({ curricula }) {
  return (
    <>
      <Head>
        <title>LBPS Curriculum Warehouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Section>
          <h2>Introductory Heading</h2>
          <p>
            Introductory paragraph explaining how this site is organized. Lorem
            ipsum dolor sit amet consectetur adipisicing elit. Sit
            exercitationem laborum consectetur voluptas recusandae, ab, quo
            voluptates odio ad nisi quod, repudiandae ex iure delectus molestiae
            eum quidem placeat unde.
          </p>
        </Section>
        <Section>
          <h2>Select a Grade Span/Band</h2>
        </Section>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const req = await fetch("http://localhost:3000/api/sheets");
  const res = await req.json();
  res.data.shift();
  const curricula = createCurriculaObject(res.data);
  console.log("CURRICULA OBJECT = ", curricula);
  return {
    props: { curricula: res.data },
  };
}
